# Generated by Django 4.0.4 on 2022-05-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_playlist_url_alter_playlist_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='', upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='playlist',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
