# Generated by Django 4.0.4 on 2022-05-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_playlist_image_playlist_tag_playlist_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='', upload_to='media/covers/'),
        ),
    ]
