# Generated by Django 4.0.4 on 2022-05-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_tag_playlist_tags_alter_playlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='tags',
            new_name='tags_author',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tags_playlist',
            field=models.CharField(default='', max_length=100),
        ),
    ]
