# Generated by Django 4.0.4 on 2022-05-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_contact_post_suscriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tags_author',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tags_playlist',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
